---
- name: Check Ubuntu distro is supported
  get_url: url="https://deb.nodesource.com/node/dists/{{ ansible_distribution_release }}/Release" dest=/dev/null
  register: distro_supported

- name: Remove old Chris Lea' ppa
  when: distro_supported|success
  apt_repository: repo='ppa:{{ node_ppa }}' state=absent

- name: Remove old 'Chris Lea' sources
  when: distro_supported|success
  file: path="/etc/apt/sources.list.d/chris-lea-node_js-{{ ansible_distribution_release }}.list" state=absent

- name: Add nodesource keys
  when: distro_supported|success
  apt_key: url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key" state=present

- name: Add nodesource apt sources list deb
  when: distro_supported|success
  apt_repository: |
    repo="deb https://deb.nodesource.com/node {{ ansible_distribution_release }} main"
    state=present

- name: Add nodesource apt sources list deb src
  when: distro_supported|success
  apt_repository: |
    repo="deb-src https://deb.nodesource.com/node {{ ansible_distribution_release }} main"
    state=present

- name: Install nodejs!
  when: distro_supported|success
  apt: pkg=nodejs state=latest update_cache=true
